name: Build on Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository  code
        uses: actions/checkout@v2

      - name: Install SFML
        run: |
          sudo apt-get update
          sudo apt-get install libsfml-dev

      - name: Build with CMake
        run: |
        cmake --build ${{github.workspace}}/build \
              --config ${{env.BUILD_TYPE}}

      - name: Test with CMake
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
