name: Build on Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository  code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Initialize repository
        working-directory: ${{github.workspace}}
        run: make init

      - name: Install SFML
        run: |
          sudo apt-get update
          sudo apt-get install libsfml-dev

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -H${{github.workspace}} -B${{github.workspace}}/build -G "Unix Makefiles"

      - name: Build with CMake
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test with CMake
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
